name: CI Workflow

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Dummy JavaScript File (if needed)
        run: echo "console.log('Dummy file for ESLint');" > dummy.js

      - name: Create package.json
        run: |
          echo '{
            "name": "ci-workflow",
            "version": "1.0.0",
            "scripts": {
              "lint": "eslint \"**/*.js\" || true",
              "test": "echo \"No tests configured\" && exit 0"
            },
            "devDependencies": {
              "eslint": "^8.0.0"
            }
          }' > package.json

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

  test:
    name: Run Tests (Placeholder)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create package.json
        run: |
          echo '{
            "name": "ci-workflow",
            "version": "1.0.0",
            "scripts": {
              "lint": "eslint .",
              "test": "echo \"No tests configured\" && exit 0"
            },
            "devDependencies": {
              "eslint": "^8.0.0"
            }
          }' > package.json

      - name: Install Dependencies
        run: npm install

      - name: Run Placeholder Test
        run: npm run test
